### ISSUE TITLE
it's not collecting statistics

### ISSUE THREAD

**Issue by sathia-musso** [varnish/newrelic_varnish_plugin#5]
HTTP04:/usr/src/newrelic_varnish_plugin-master$ cat  config/newrelic_plugin.yml
newrelic:
    license_key: 'MY_KEY'
    verbose: 1
    host: "collector.newrelic.com"
agents:
    varnish:
        -
          name: "HTTP04"
          vname: ""

HTTP04:/usr/src/newrelic_varnish_plugin-master$ ./newrelic_varnish_plugin
Faraday: you may want to install system_timer for reliable timeouts
[Wed Jun 26 09:53:58 UTC 2013] Agent Varnish is at version 0.0.4
can't convert Array into String: ./newrelic_varnish_plugin:77:in `popen'
  ./newrelic_varnish_plugin:77:in`varnishstat'
  ./newrelic_varnish_plugin:137:in `poll_cycle'
  /var/lib/gems/1.8/gems/newrelic_plugin-1.0.3/lib/newrelic_plugin/agent.rb:143:in`run'
  /var/lib/gems/1.8/gems/newrelic_plugin-1.0.3/lib/newrelic_plugin/run.rb:95:in `loop_forever'
  /var/lib/gems/1.8/gems/newrelic_plugin-1.0.3/lib/newrelic_plugin/run.rb:93:in`each'
  /var/lib/gems/1.8/gems/newrelic_plugin-1.0.3/lib/newrelic_plugin/run.rb:93:in `loop_forever'
  /var/lib/gems/1.8/gems/newrelic_plugin-1.0.3/lib/newrelic_plugin/run.rb:17:in`setup_and_run'
  ./newrelic_varnish_plugin:185
[Wed Jun 26 09:53:58 UTC 2013] Gathered 0 statistics
^C[Wed Jun 26 09:54:06 UTC 2013] Shutting down...
[Wed Jun 26 09:54:06 UTC 2013] Shutdown complete

not sure why, any idea would be greatly appreciated.
thanks

**Comment by sathia-musso** [comment]
I fixed the issue by assigning the vname parameter. probably I misunderstood the documentation.
