### ISSUE TITLE
Error while launching the plugin

### ISSUE THREAD

**Issue by crivabene** [varnish/newrelic_varnish_plugin#7]
Hello,

Launching the plugin on CentOS, I get the following error:

[2013-07-03 08:41:29 UTC] Agent Varnish is at version 0.0.4
Unknown unit: sm_balloc: ./newrelic_varnish_plugin:139:in `unit'
  ./newrelic_varnish_plugin:172:in`report'
  ./newrelic_varnish_plugin:151:in `block (2 levels) in poll_cycle'
  ./newrelic_varnish_plugin:146:in`each'
  ./newrelic_varnish_plugin:146:in `block in poll_cycle'
  ./newrelic_varnish_plugin:145:in`each'
  ./newrelic_varnish_plugin:145:in `poll_cycle'
  /usr/local/rvm/gems/ruby-2.0.0-p195/gems/newrelic_plugin-1.0.3/lib/newrelic_plugin/agent.rb:143:in`run'
  /usr/local/rvm/gems/ruby-2.0.0-p195/gems/newrelic_plugin-1.0.3/lib/newrelic_plugin/run.rb:95:in `block in loop_forever'
  /usr/local/rvm/gems/ruby-2.0.0-p195/gems/newrelic_plugin-1.0.3/lib/newrelic_plugin/run.rb:93:in`each'
  /usr/local/rvm/gems/ruby-2.0.0-p195/gems/newrelic_plugin-1.0.3/lib/newrelic_plugin/run.rb:93:in `loop_forever'
  /usr/local/rvm/gems/ruby-2.0.0-p195/gems/newrelic_plugin-1.0.3/lib/newrelic_plugin/run.rb:17:in`setup_and_run'
  ./newrelic_varnish_plugin:192:in `<module:VarnishAgent>'
  ./newrelic_varnish_plugin:40:in`<main>'
[2013-07-03 08:41:29 UTC] Gathered 28 statistics

Thanks,
Claudio

**Comment by darthsteven** [comment]
This would seem to be just because the code doesn't handle the units of 'sm_balloc' correctly.

**Comment by darthsteven** [comment]
The pull request got in, so did you want to re-test this issue, or close it?

**Comment by tfheen** [comment]
If you could please retest, that'd be appreciated.
